services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USE_CELERY: ${USE_CELERY:-true}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./temp:/app/temp
    env_file:
      - config/backend.dev.env
    command: python -m uvicorn fastapi_main:app --host 0.0.0.0 --port 8000 --reload

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "${VITE_DEV_SERVER_PORT:-5173}:${VITE_DEV_SERVER_PORT:-5173}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - config/frontend.dev.env
    command: pnpm run dev -- --host ${VITE_DEV_SERVER_HOST:-0.0.0.0} --port ${VITE_DEV_SERVER_PORT:-5173}

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --save 300 100
    profiles:
      - celery

  celery:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USE_CELERY: ${USE_CELERY:-true}
    volumes:
      - ./backend:/app
      - ./temp:/app/temp
    env_file:
      - config/backend.dev.env
    depends_on:
      - redis
      - backend
    command: celery -A celery_app worker --loglevel=debug
    profiles:
      - celery

  celery-beat:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USE_CELERY: ${USE_CELERY:-true}
    volumes:
      - ./backend:/app
      - ./temp:/app/temp
    env_file:
      - config/backend.dev.env
    depends_on:
      - redis
      - backend
    command: celery -A celery_app beat --loglevel=debug --schedule=/app/temp/celerybeat-schedule
    profiles:
      - celery

volumes:
  redis_data: