# Base docker-compose configuration
# Common settings shared between dev and production

services:
  backend:
    image: ${DOCKER_IMAGE_BACKEND}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - config/backend.base.env
      - config/backend.${ENVIRONMENT:-development}.env
    restart: ${RESTART_POLICY:-no}

  frontend:
    image: ${DOCKER_IMAGE_FRONTEND}
    env_file:
      - config/frontend.base.env
      - config/frontend.${ENVIRONMENT:-development}.env
    restart: ${RESTART_POLICY:-no}

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: ${RESTART_POLICY:-no}
    profiles:
      - celery

  celery:
    image: ${DOCKER_IMAGE_CELERY_WORKER}
    env_file:
      - config/backend.base.env
      - config/backend.${ENVIRONMENT:-development}.env
    depends_on:
      - redis
      - backend
    restart: ${RESTART_POLICY:-no}
    profiles:
      - celery

  celery-beat:
    image: ${DOCKER_IMAGE_CELERY_BEAT}
    env_file:
      - config/backend.base.env
      - config/backend.${ENVIRONMENT:-development}.env
    depends_on:
      - redis
      - backend
    restart: ${RESTART_POLICY:-no}
    profiles:
      - celery

volumes:
  redis_data:
    driver: local